[Feature] Allow the automatic detection of the source language #60
hergetto/deepl_ex pull request #61
Opened 2024-07-21 11:14 UTC by nwittstruck

Closes #60 

# Description

This PR adds `:DETECT` as a supported language. This allows the DeepL API to detect the source language automatically.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [X] added tests

2024-08-19 19:58 UTC, dustessavdh requested changes

2024-08-19 19:58 UTC, dustessavdh commented on config/config.exs
This breaks the library, could you remove this and the unit test.
Unit tests are nice, however in this case I don't think it will add much.

2024-08-20 07:08 UTC, nwittstruck commented on config/config.exs
Hi @dustessavdh , thank you for taking a look! Sure, I can remove that. I've just updated the branch.

Out of curiosity - what broke with the config? I've used the package with 
`{:deepl_ex, git: "https://github.com/b310-digital/deepl_ex.git", branch: "60-allow-detection-of-source-language"}` during testing and it worked.

2024-08-25 11:37 UTC, dustessavdh approved these changes
LGTM!

2024-08-25 11:37 UTC, dustessavdh commented on config/config.exs
I tried running it from `iex -S mix` and couldn't make it work

2024-08-25 11:38 UTC, dustessavdh commented
Thank you for contributing! Sorry for the long wait.

2024-08-25 11:38 UTC, merged